### ISSUE TITLE
Playbook Overview

### ISSUE THREAD

**Issue by garethventon** [EqualExperts/secure-delivery-playbook#1]
Good Afternoon,

Firstly many thanks for producing this I have found it to cover a number of well published topics but in a clear and concise way hence I have started sharing with a number of colleagues.

I'd love to help contribute and adapt some of our ways of working based on it and wondered if anyone would be available within EE to walk through the doc and do a bit more Q&A.

I'm based in Federation House working for the Co-op so if also in fed that would be great.

Thanks,

**Comment by stuartgunter** [comment]
Hi Gareth

Thanks for your feedback... it's great to hear you're finding the playbook useful.

We'll get in touch with you shortly to see how we can help.
